/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install and kept here so the
// initial scaffold type-checks once dependencies are installed.
