export const API_ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  GEOGRAPHY_NOT_SELECTABLE: "GEOGRAPHY_NOT_SELECTABLE",
  REPORT_BLOCKED: "REPORT_BLOCKED",
  LOW_CONFIDENCE_ACK_REQUIRED: "LOW_CONFIDENCE_ACK_REQUIRED",
  PAYMENT_NOT_CONFIRMED: "PAYMENT_NOT_CONFIRMED",
  NO_REPORT_ENTITLEMENT: "NO_REPORT_ENTITLEMENT",
  PROFILE_INCOMPLETE: "PROFILE_INCOMPLETE",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED"
} as const;

export type ApiErrorCode = keyof typeof API_ERROR_CODES;
